### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by oluwandabira** [TalTech-HPC-Centre/taltech-hpc-docs#1]
There might be a bunch of dead links left over like [this one](https://github.com/TalTech-HPC-Centre/taltech-hpc-docs/blob/main/docs/index.md?plain=1#L37) (which points here <https://base.hpc.taltech.ee/load/>).

**Comment by JamFox** [comment]
Done in https://github.com/TalTech-HPC-Centre/taltech-hpc-docs/commit/4848e3212f16534f1165867d50f82c91448a2251
